DESC EMPLE

/*primer*/


CREATE TABLE EMPLEADOS30
AS SELECT * FROM EMPLE WHERE DEPT_NO=30;

DESC EMPLEADOS30

ALTER TABLE EMPLEADOS30 
ADD (CONSTRAINT E30_PK PRIMARY KEY (EMP_NO));


ALTER TABLE EMPLEADOS30
ADD( CONSTRAINT E30_DEPART_FK FOREIGN KEY (DEPT_NO) REFERENCES DEPART);

ALTER TABLE EMPLEADOS30
ADD(CONSTRAINT E30_FK FOREIGN KEY (ID_JEFE) REFERENCES EMPLEADOS30(EMP_NO))
;

/*
Error que empieza en la línea: 19 del comando :
ALTER TABLE EMPLEADOS30
ADD(CONSTRAINT E30_FK FOREIGN KEY(ID_JEFE)REFERENCES EMPLEADOS30(EMP_NO))
Informe de error -
ORA-02298: no se puede validar (DAW21.E30_FK) - claves principales no encontradas
02298. 00000 - "cannot validate (%s.%s) - parent keys not found"
*Cause:    an alter table validating constraint failed because the table has
           child records.
*Action:  Modificamos la tabla empleados30 para que no exisitan valores que no 
sean empleados.
*/

SELECT * FROM EMPLEADOS30;

UPDATE EMPLEADOS30 
    SET ID_JEFE=NULL
    WHERE ID_JEFE NOT IN (SELECT EMP_NO 
                FROM EMPLEADOS30);
                
 /*Despues de modificar los datos hacemos el alter*/               
ALTER TABLE EMPLEADOS30
ADD(CONSTRAINT E30_FK FOREIGN KEY (ID_JEFE) REFERENCES EMPLEADOS30(EMP_NO))
;



SELECT USER_CONSTRAINTS.CONSTRAINT_NAME,CONSTRAINT_TYPE,SEARCH_CONDITION,
        USER_CONS_COLUMNS.*
        FROM USER_CONSTRAINTS,USER_CONS_COLUMNS
        WHERE UPPER(USER_CONSTRAINTS.TABLE_NAME)= 'EMPLEDOS'
        AND 
        USER_CONSTRAINTS.CONSTRAINT_NAME=USER_CONS_COLUMNS.CONSTRAINT_NAME --JOIN
;

SELECT USER_CONSTRAINTS.CONSTRAINT_NAME,CONSTRAINT_TYPE,SEARCH_CONDITION,
        USER_CONS_COLUMNS.*
        FROM USER_CONSTRAINTS,USER_CONS_COLUMNS
        WHERE UPPER(USER_CONSTRAINTS.TABLE_NAME)= 'EMPLEADOS30'
        AND 
        USER_CONSTRAINTS.CONSTRAINT_NAME=USER_CONS_COLUMNS.CONSTRAINT_NAME --JOIN
;






/*uno*/
INSERT INTO EMPLE (EMP_NO, APELLIDO, OFICIO, 
FECHA_ALTA, SALARIO, COMISION_PCT, DEPT_NO,ID_JEFE) 
SELECT 2000,'SAAVEDRA',oficio,SYSDATE,salario+salario*0.2,
        comision_pct,dept_no,id_jefe
FROM EMPLE
WHERE lower(emple.apellido)='sala'
;


select*FROM EMPLE
WHERE LOWER(apellido)IN('sala','saavedra');



/*DOS*/
SET DEPT_NO=(SELECT * FROM EMPLE WHERE EMP_NO=7499)
WHERE OFICIO=(SELECT OFICIO FROM EMPLE WHERE EMP_NO=7566)



DELETE FROM DEPART WHERE DEPT_NO NOT IN





DELETE FROM DEPART
WHERE INITCAP(DNOMBRE)LIKE '%O%';



update emple set salario=salario + (SELECT COMISION_PCT
FROM EMPLE WHERE UPPER(APELLIDO)='ARROYO')
where UPPER(APELLIDO)='REY';



ROLLBACK;


SELECT COUNT(*)
FROM EMPLE
WHERE UPPER(OFICIO)='PROGRAMADOR';

UPDATE EMPLE SET dept_no=(SELECT DEPT_NO
                FROM EMPLE
                WHERE UPPER(OFICIO)='PROGRAMADOR'
                GROUP BY DEPT_NO
HAVING COUNT(*)=(SELECT MAX(COUNT(*)FROM EMPLE)
                WHERE UPPER(OFICIO)='PROGRAMADOR'
                GROUP BY DEPT_NO);
























/*EJER1 VARIAS Tablas*/


SELECT APELLIDO OFICIO EMP_NO, DNOMBRE LOC
FROM EMPLE,DEPART
WHERE EMPLE.DEPT_NO = DEPART.DEPT_NO --JOIN
;


SELECT EMPLE.*, DEPART.LOC
FROM EMPLE, DEPART
    WHERE EMPLE.DEPT_NO=DEPART.DEPT_NO 
    AND UPPER(DEPART.LOC) IN ('MADRID','BARCELONA');



SELECT e.emp_no,e.apellido, j.apellido "su jefe es"
FROM EMPLE e, EMPLE j
WHERE e.id_jefe = j.emp_no
;










































