DESC USER_CONSTRAINTS

DESC USER_CONS_COLUMNS

DESC EMPLEADOS30


SELECT * FROM EMPLEADOS30;

UPDATE EMPLEADOS30 
    SET ID_JEFE=NULL
    WHERE ID_JEFE NOT IN (SELECT EMP_NO 
                FROM EMPLEADOS30);

